version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /task
  script: trending.application
  #login: required

- url: /autocompletecorn
  script: search.application

- url: /autocompletelist
  script: search.application

- url: /clean
  script: trending.application
  #login: required

- url: /createstream
  script: createstream.application
  login: required

- url: /geoview.*
  script: viewsinglestream.application
  login: required

- url: /uploadurlhandler
  script: viewsinglestream.application
  login: required

- url: /sign
  script: createstream.application
  login: required

- url: /viewallstreams
  script: view.application
 # login: required




- url: /showsearch
  script: search.application
  login: required

- url: /error
  script: error.application
  login: required

- url: /trending
  script: trending.application
  login: required

- url: /update
  script: trending.application
  #login: required

- url: /management
  script: management.application
  login: required

- url: /delstream
  script: management.application
  login: required

- url: /stream.*
  script: viewsinglestream.application
  login: required

- url: /upload
  script: viewsinglestream.application
  login: required

- url: /showmore.*
  script: viewsinglestream.application
  login: required

- url: /delpic
  script: viewsinglestream.application
  login: required

- url: /subscribe
  script: viewsinglestream.application

- url: /view_photo.*
  script: viewsinglestream.application
  login: required

- url: /androidViewNearbyPhotos.*
  script: view.application


- url: /viewAllPhotos
  script: view.application

- url: /mySubscribe
  script: view.application

- url: /viewSingleStream
  script: viewsinglestream.application

- url: /getUploadURL
  script: viewsinglestream.application

- url: /uploadFromAndroid
  script: viewsinglestream.application

- url: /search
  script: search.application

- url: /lowerSubscribeList
  script: viewsinglestream.application


- url: /.*
  script: login.application



#- url: /img.*
 # script: viewsinglestream.application
  #login: required

libraries:
- name: webapp2
  version: latest
- name: PIL
  version: latest
- name: jinja2
  version: latest


